# Gnome stuff
[Match]
Profiles=gnome
Distribution=fedora

[Distribution]
Repositories=terra

[Build]
SandboxTrees=
    ../../mkosi.global-repos/terra.repo:/etc/yum.repos.d/terra.repo
    ../../mkosi.global-repos/um.repo:/etc/yum.repos.d/um.repo

[Content]
Splash=/usr/share/pixmaps/fedora-logo.png
WithRecommends=true
RemovePackages=
    firefox libreoffice
Packages=
    --allowerasing
    @ultramarine-gnome-product-environment
    # ultramarine-release-atomic-gnome
    gnome-tweaks
    gnome-shell
    gdm
    ptyxis
    gnome-disk-utility
    gnome-keyring
    gnome-keyring-pam
    nautilus
    nautilus-python
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk