# Minimal setup

[Match]
Distribution=fedora

[Distribution]
Distribution=fedora
Architecture=x86-64
Release=43

[Build]
SandboxTrees=
    mkosi.global-repos/ublue.repo:/etc/yum.repos.d/ublue.repo,
    mkosi.global-repos/terra.repo:/etc/yum.repos.d/terra.repo,
    mkosi.global-repos/um.repo:/etc/yum.repos.d/um.repo

[Content]
# Splash=/usr/share/pixmaps/fedora-logo.png
WithRecommends=true
VolatilePackages=
    systemd
    systemd-boot
    systemd-container
    systemd-oomd-defaults
    systemd-resolved
    udev
    shim-x64
    shim-unsigned-x64
Packages=
    terra-release
    open-vm-tools
    vim
    sudo
    distribution-gpg-keys
    ntfs-3g
    xfsprogs
    btrfs-progs
    lvm2
    firewalld
    git
    make
    distrobox
    binutils
    curl
    gcc
    wget
    tmux
    podman
    unzip
    wireguard-tools    
    rsync
    bash
    linux-firmware
    kernel
    kernel-devel
    kernel-headers
    kernel-modules
    uupd
    zram-generator
    grub2
    grub2-common
    grub2-efi-x64
