# Desktop stuff
[Match]
Profiles=desktop
Distribution=fedora

[Distribution]
Repositories=terra

[Build]
SandboxTrees=
    ../../mkosi.global-repos/terra.repo:/etc/yum.repos.d/terra.repo
    ../../mkosi.global-repos/um.repo:/etc/yum.repos.d/um.repo

[Content]
Splash=/usr/share/pixmaps/fedora-logo.png
WithRecommends=true
Packages=
    spice-vdagent
    mesa-dri-drivers
    adobe-source-code-pro-fonts
    adwaita-mono-fonts
    adwaita-sans-fonts
    audispd-plugins
    cups
    cups-browsed
    cups-ipptool
    cups-pk-helper
    ddcutil
    default-fonts
    default-fonts-core-emoji
    dymo-cups-drivers
    flatpak
    fpaste
    fprintd
    gi-docgen-fonts
    google-noto-color-emoji-fonts
    google-noto-emoji-fonts
    gvfs-fuse
    gvfs-mtp
    gvfs-smb
    hplip
    ifuse
    just
    libcamera
    libcamera-gstreamer
    libcamera-ipa
    libcamera-tools
    libcamera-v4l2
    liberation-mono-fonts
    openssh-askpass
    orca
    pipewire
    pipewire-alsa
    pipewire-gstreamer
    pipewire-jack-audio-connection-kit
    pipewire-plugin-libcamera
    pipewire-pulseaudio
    pipewire-utils
    printer-driver-brlaser
    redhat-display-fonts
    redhat-text-fonts
    sane-backends
    sane-backends-drivers-cameras
    sane-backends-drivers-scanners
    usbmuxd
    uxplay
    webp-pixbuf-loader
    wireplumber
    wl-clipboard
    xdg-terminal-exec
    xdg-user-dirs
    xdg-utils
    xorg-x11-server-Xwayland
    tuned-ppd
    tuned-profiles-atomic
    steam-device-rules
    8bitdo-udev-rules
    android-udev-rules
    ffmpeg
    readymade
    readymade-config-ultramarine
    plymouth
    taidan